general.live_config_reload = true
scrolling.history = 0
mouse.hide_when_typing = true

[window]
decorations = "none"
opacity = 1.0
option_as_alt = "Both"
startup_mode = "SimpleFullscreen"

[font]
size = 11.0
offset = { x = 0, y = 4 }

[colors]
draw_bold_text_with_bright_colors = true
primary = { background = "0x000000", foreground = "0xffffff" }

[colors.bright]
black = "0x808080"
blue = "0x0066ff"
cyan = "0x00ffff"
green = "0x33ff00"
magenta = "0xcc00ff"
red = "0xfe0100"
white = "0xFFFFFF"
yellow = "0xfeff00"

[colors.normal]
black = "0x000000"
blue = "0x0066ff"
cyan = "0x00ffff"
green = "0x33ff00"
magenta = "0xcc00ff"
red = "0xfe0100"
white = "0xd0d0d0"
yellow = "0xfeff00"

[keyboard]
bindings = [
  { key="V",   mods="Command", action="Paste"            },
  { key="C",   mods="Command", action="Copy"             },
  { key="Q",   mods="Command", action="Quit"             },
  { key="W",   mods="Command", action="Quit"             },
  { key="0",   mods="Command", action="ResetFontSize"    },
  { key="-",   mods="Command", action="DecreaseFontSize" },
  { key="=",   mods="Command", action="IncreaseFontSize" },
]
